trigger:
- main
- develop

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore

- task: PowerShell@2
  displayName: 'Build Connectors'
  inputs:
    targetType: 'inline'
    script: |
        cd .\Connectors
        .\build.ps1 $(buildConfiguration)

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployExtension=false /p:AppInsightsInstrumentationKey=$(AppInsightsInstrumentationKey) /nowarn:VSTHRD010'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  displayName: Run SpecFlow Scenarios
  inputs:
    command: test
    projects: '**/*[Ss]pecs/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --runtime win-x64'
    testRunTitle: 'Deveroom Specs'

- task: CopyFiles@2
  displayName: 'Copy dlls and changelog'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     **\bin\$(buildConfiguration)\**
     Changelog.md
    TargetFolder: '$(build.artifactstagingdirectory)\drop'
  condition: succeededOrFailed()

- task: CopyFiles@2
  displayName: 'Copy marketplace scripts'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     publish*.ps1
     .marketplace\**
    TargetFolder: '$(build.artifactstagingdirectory)\marketplace'
  condition: succeededOrFailed()

- task: CopyFiles@2
  displayName: 'Copy NuGet folder'
  inputs:
    SourceFolder: 'd:\a\1\Nuget'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)\drop\NuGet'
  condition: succeededOrFailed()

- task: CopyFiles@2
  displayName: 'Copy VSIX'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(buildConfiguration)\**\*.vsix'
    TargetFolder: '$(build.artifactstagingdirectory)\vsix'
    flattenFolders: true
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\drop'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: marketplace'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\marketplace'
    ArtifactName: marketplace
  condition: succeededOrFailed()
 
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: vsix'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\vsix'
    ArtifactName: vsix
  condition: succeededOrFailed()
